server {
  listen 80;
  location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri $uri/ /index.html;
  }

  location /auth/ {
      proxy_pass http://planeo-gateway:8080/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/sse {
    proxy_pass http://planeo-gateway:8080/api/sse;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 24h;
    proxy_send_timeout 24h;
    chunked_transfer_encoding on;
    add_header Cache-Control no-cache;
    add_header X-Accel-Buffering no;
  }

  location /api/ {
      proxy_pass http://planeo-gateway:8080/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
  }

}
